import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        socra: {
          darkest: '#333d29',
          dark: '#414833',
          forest: '#656d4a',
          sage: '#a4ac86',
          stone: '#c2c5aa',
          tan: '#b6ad90',
          sand: '#a68a64',
          midbrown: '#936639',
          deepbrown: '#7f4f24',
          richbrown: '#582f0e',
        },
        'primary-container': '#656d4a',
        'on-surface': '#ece2c3',
        'on-secondary-fixed-variant': '#434a2b',
        'inverse-surface': '#ece2c3',
        'surface-dim': '#171303',
        'surface-container-high': '#2f2a15',
        'on-secondary-container': '#b1b992',
        'tertiary-container': '#7e6542',
        'surface-tint': '#c2cba1',
        'surface-container': '#241f0c',
        primary: '#c2cba1',
        'on-surface-variant': '#c7c7bb',
        outline: '#919286',
        'on-primary-fixed-variant': '#424a2a',
        'on-primary-container': '#e6efc3',
        'on-secondary': '#2c3317',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#594323',
        'surface-container-highest': '#3a351f',
        'primary-fixed': '#dee7bc',
        'surface-container-lowest': '#120e01',
        'surface-variant': '#3a351f',
        'secondary-fixed-dim': '#c3cba3',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#e1c298',
        error: '#ffb4ab',
        'secondary-fixed': '#dfe7bd',
        'on-tertiary': '#402d0f',
        'primary-fixed-dim': '#c2cba1',
        'on-secondary-fixed': '#181e05',
        surface: '#171303',
        'on-error': '#690005',
        'secondary-container': '#434a2b',
        'on-primary-fixed': '#181e04',
        'surface-bright': '#3f3923',
        'on-primary': '#2c3316',
        secondary: '#c3cba3',
        tertiary: '#e1c298',
        'on-background': '#ece2c3',
        'inverse-primary': '#5a6240',
        'inverse-on-surface': '#36301b',
        'outline-variant': '#46483e',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#201b08',
        'on-tertiary-container': '#ffe6c8',
        'tertiary-fixed': '#ffddb2',
        background: '#171303',
        mastered: '#a4ac86',
        shaky: '#936639',
        forgotten: '#582f0e',
      },
      spacing: {
        'stack-lg': '32px',
        'stack-sm': '8px',
        'container-margin': '24px',
        'stack-md': '16px',
        gutter: '16px',
        unit: '8px',
        'section-gap': '48px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Lora', 'serif'],
        'label-lg': ['DM Sans', 'sans-serif'],
        'body-md': ['Literata', 'serif'],
        'headline-md': ['DM Sans', 'sans-serif'],
        'label-sm': ['DM Sans', 'sans-serif'],
        'headline-lg-mobile': ['DM Sans', 'sans-serif'],
        display: ['DM Sans', 'sans-serif'],
        'headline-lg': ['DM Sans', 'sans-serif'],
        'body-lg': ['Literata', 'serif'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      boxShadow: {
        glow: '0 0 0 1px rgba(147, 102, 57, 0.35), 0 18px 60px rgba(51, 61, 41, 0.45)',
      },
      backgroundImage: {
        'socra-grid':
          'linear-gradient(rgba(164, 172, 134, 0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(164, 172, 134, 0.08) 1px, transparent 1px)',
      },
    },
  },
  plugins: [],
}

export default config