import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        socra: {
          darkest: '#fafaf1',
          dark: '#f0f1e7',
          forest: '#656d4a',
          sage: '#a4ac86',
          stone: '#1a1c16',
          tan: '#b6ad90',
          sand: '#a68a64',
          midbrown: '#936639',
          deepbrown: '#7f4f24',
          richbrown: '#582f0e',
        },
        'primary-container': '#656d4a',
        'on-surface': '#1a1c16',
        'on-secondary-fixed-variant': '#434a2b',
        'inverse-surface': '#1a1c16',
        'surface-dim': '#dadbd2',
        'surface-container-high': '#e8e9e0',
        'on-secondary-container': '#b1b992',
        'tertiary-container': '#7e6542',
        'surface-tint': '#5a6240',
        'surface-container': '#f0f1e7',
        primary: '#5a6240',
        'on-surface-variant': '#46483e',
        outline: '#76786b',
        'on-primary-fixed-variant': '#424a2a',
        'on-primary-container': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#594323',
        'surface-container-highest': '#e2e3d9',
        'primary-fixed': '#dee7bc',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e3e4d3',
        'secondary-fixed-dim': '#c3cba3',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#e1c298',
        error: '#ba1a1a',
        'secondary-fixed': '#dfe7bd',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#c2cba1',
        'on-secondary-fixed': '#181e05',
        surface: '#fafaf1',
        'on-error': '#ffffff',
        'secondary-container': '#434a2b',
        'on-primary-fixed': '#181e04',
        'surface-bright': '#fafaf1',
        'on-primary': '#ffffff',
        secondary: '#5b6146',
        tertiary: '#7e570f',
        'on-background': '#1a1c16',
        'inverse-primary': '#c2cba1',
        'inverse-on-surface': '#f4f1e8',
        'outline-variant': '#c7c7bb',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#f4f4eb',
        'on-tertiary-container': '#ffe6c8',
        'tertiary-fixed': '#ffddb2',
        background: '#fafaf1',
        mastered: '#a4ac86',
        shaky: '#936639',
        forgotten: '#582f0e',
      },
      spacing: {
        'stack-lg': '32px',
        'stack-sm': '8px',
        'container-margin': '24px',
        'stack-md': '16px',
        gutter: '16px',
        unit: '8px',
        'section-gap': '48px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Lora', 'serif'],
        'label-lg': ['DM Sans', 'sans-serif'],
        'body-md': ['Literata', 'serif'],
        'headline-md': ['DM Sans', 'sans-serif'],
        'label-sm': ['DM Sans', 'sans-serif'],
        'headline-lg-mobile': ['DM Sans', 'sans-serif'],
        display: ['DM Sans', 'sans-serif'],
        'headline-lg': ['DM Sans', 'sans-serif'],
        'body-lg': ['Literata', 'serif'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      boxShadow: {
        glow: '0 0 0 1px rgba(90, 98, 64, 0.15), 0 18px 60px rgba(0, 0, 0, 0.08)',
      },
      backgroundImage: {
        'socra-grid':
          'linear-gradient(rgba(70, 72, 62, 0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(70, 72, 62, 0.06) 1px, transparent 1px)',
      },
    },
  },
  plugins: [],
}

export default config